### ISSUE TITLE
Typo in BaggageTypeEnumeration: MUSICALNSTRUMENT

### ISSUE THREAD

**Issue by upendra-vedullapalli** [entur/netex-java-model#20]
Hi, 
BaggageTypeEnumeration value 'MUSICALNSTRUMENT' is misspelled and missing an 'I' in INSTRUMENT.
It would be nice if this can be fixed.

Thanks,
Upendra

**Comment by skinkie** [comment]
> Hi, BaggageTypeEnumeration value 'MUSICALNSTRUMENT' is misspelled and missing an 'I' in INSTRUMENT. It would be nice if this can be fixed.
> 
> Thanks, Upendra

Please report this issue at the source in the future :-) https://github.com/NeTEx-CEN/NeTEx/

**Comment by vpaturet** [comment]
Fixed in v1.14
