### ISSUE TITLE
Add a xjc plugin to allow the objects to be clonable

### ISSUE THREAD

**Issue by skinkie** [entur/netex-java-model#6]
The problem at this moment with inference and NeTEx is that if objects must be duplicated cloning would be really benificial. There are several options for cloning JAXB objects one of is marshall and unmarshall, which is very slow, alternatives exists, such as cc-xjc. Could this be added to the pom file as plugin?

Alternatives:
https://github.com/highsource/jaxb2-basics/wiki#jaxb2-basics-plugins

**Comment by skinkie** [comment]
Implemented by pull #8

**Comment by assadriaz** [comment]
@erlendnils1 Do have time to review this pull request, thanks.

**Comment by erlendnils1** [comment]
Looks like a nice feature. Merged into master
